### ISSUE TITLE
Requesting large number of metrics leads to task hang

### ISSUE THREAD

**Issue by marcin-krolik** [intelsdi-x/snap#662]
I found out requesting large number of metrics (around 500 is enough) from any collector plugin leads to task hang. 
Issue was check with lower number of metrics (50, 100, 200, 300) and there was no error.

Reproduction:
1. Load file publisher
```bash
$ $SNAP_PATH/bin/snapctl plugin load  build/plugin/snap-publisher-file
```
2. Load plugin 
```bash
$ $SNAP_PATH/bin/snapctl plugin load <plugin_name>
```
3. Prepare task manifest with more then 500 metrics (example attached)
4. Create task
```bash
$SNAP_PATH/bin/snapctl task create -t examples/task/task.json
```
5. Try to watch task
```bash
$SNAP_PATH/bin/snapctl task watch <id>
```

Fails:
Task watcher starts but no output shows up.
File publisher produces only 1 iteration of results, then no new content published
It is not possible to stop started task with
```bash
$SNAP_PATH/bin/snapctl task stop <id>
```
Task stays on the list of tasks with state "Running"

Publisher plugin, collector plugin heartbeat leaves. It is possible to unload publisher and collector.

[files_and_logs.zip](https://github.com/intelsdi-x/snap/files/82810/files_and_logs.zip)

**Comment by jcooklin** [comment]
Hi @marcin-krolik, will you push the source for snap-plugin-collector-processes.

**Comment by thomastaylor312** [comment]
Just as a note, I have seen this too with a plugin that gets a metric ton of data once a day.

**Comment by jcooklin** [comment]
@marcin-krolik @thomastaylor312: #664 should fix this issue.  When you have time please test it.

**Comment by thomastaylor312** [comment]
I won't be back in to a place where I can test it until Monday. I'll do
that first thing.

**Comment by marcin-krolik** [comment]
Hi @jcooklin, I created PR for processes 
https://github.com/intelsdi-x/snap-plugin-collector-processes/pull/1
I also reproduced this bug with dummy plugin which generates arbitrary number of metrics. It seems there is cut off at exactly 500 metrics which  leads to this hang.

**Comment by jcooklin** [comment]
Hi @marcin-krolik, did you test your processes plugin against #664?

**Comment by thomastaylor312** [comment]
@jcooklin I am still seeing the issue even with #664. It runs once and then doesn't run again.

**Comment by jcooklin** [comment]
I successfully tested against @marcin-krolik process plugin [here](https://github.com/intelsdi-x/snap-plugin-collector-processes/pull/1).

```
jrcookli@jp22-4:/tmp$ snapctl task list
ID 					 NAME 						 STATE 		 HIT 	 MISS 	 FAIL 	 CREATED 		 LAST FAILURE
0e969c18-266d-42a7-9377-d162b449225b 	 Task-0e969c18-266d-42a7-9377-d162b449225b 	 Running 	 127 	 0 	 0 	 10:17AM 1-11-2016
jrcookli@jp22-4:/tmp$ head -2  snap-publisher-file.stdout
2016/01/11 10:17:06 time="2016-01-11T10:17:06-08:00" level=info msg="Publishing started"
2016/01/11 10:17:06 time="2016-01-11T10:17:06-08:00" level=info msg="publishing 10025 metrics to map[file:{/tmp/published_processes}]"
```

Notice that it has run 127 times collecting 10K metrics on each interval.

**Comment by lynxbat** [comment]
@jcooklin we are linking to a private github above.

**Comment by thomastaylor312** [comment]
I looked at the offline with @jcooklin. Looks like I had used the wrong code. #664 is working like it should.

**Comment by marcin-krolik** [comment]
Hi,
I successfully retested issue with processes plugin and with dummy plugin as well.

Thanks!
